@echo off
set "EXIT_CODE=0"

chcp 65001 1>nul 2>nul

set "HOME=%~dp0"
pushd "%HOME%"

rmdir /s /q "tmp"

mkdir "tmp" 1>nul 2>nul
pushd "%HOME%\tmp"
del /f /q "*.zone"
del /f /q "*.txt"

call "%HOME%\aria2c.exe" --no-conf "--check-certificate=false" "--user-agent=Mozilla/5.0 Windows NT 6.1" "--referer=*" "--allow-overwrite=true" "--remote-time=true" "https://www.ipdeny.com/ipblocks/data/countries/all-zones.tar.gz"
set "EXIT_CODE=%ErrorLevel%"
if ["%EXIT_CODE%"] NEQ ["0"] ( goto ERROR_ARIA2C )

call "%HOME%\7za.exe" x "all-zones.tar.gz"
set "EXIT_CODE=%ErrorLevel%"
if ["%EXIT_CODE%"] NEQ ["0"] ( goto ERROR_7ZA_GZ )

del /f /q "all-zones.tar.gz"

call "%HOME%\7za.exe" x "all-zones.tar"
set "EXIT_CODE=%ErrorLevel%"
if ["%EXIT_CODE%"] NEQ ["0"] ( goto ERROR_7ZA_TAR )

del /f /q "all-zones.tar"

call "%HOME%\unix2dos.exe" "--remove-bom" "-1252" "--oldfile" *.zone

ren "af.zone" "afghanistan__af.txt"
ren "al.zone" "albania__al.txt"
ren "dz.zone" "algeria__dz.txt"
ren "as.zone" "american_samoa__as.txt"
ren "ad.zone" "andorra__ad.txt"
ren "ao.zone" "angola__ao.txt"
ren "ai.zone" "anguilla__ai.txt"
ren "aq.zone" "antarctica__aq.txt"
ren "ag.zone" "antigua_and_barbuda__ag.txt"
ren "ap.zone" "apnic_asia_pacific_network_information_centre__ap.txt"
ren "ar.zone" "argentina__ar.txt"
ren "am.zone" "armenia__am.txt"
ren "aw.zone" "aruba__aw.txt"
ren "au.zone" "australia__au.txt"
ren "at.zone" "austria__at.txt"
ren "az.zone" "azerbaijan__az.txt"
ren "bs.zone" "bahamas__bs.txt"
ren "bh.zone" "bahrain__bh.txt"
ren "bd.zone" "bangladesh__bd.txt"
ren "bb.zone" "barbados__bb.txt"
ren "by.zone" "belarus__by.txt"
ren "be.zone" "belgium__be.txt"
ren "bz.zone" "belize__bz.txt"
ren "bj.zone" "benin__bj.txt"
ren "bm.zone" "bermuda__bm.txt"
ren "bt.zone" "bhutan__bt.txt"
ren "bo.zone" "bolivia__bo.txt"
ren "bq.zone" "bonaire_sint_eustatius_and_saba__bq.txt"
ren "ba.zone" "bosnia_and_herzegovina__ba.txt"
ren "bw.zone" "botswana__bw.txt"
ren "br.zone" "brazil__br.txt"
ren "io.zone" "british_indian_ocean_territory__io.txt"
ren "bn.zone" "brunei_darussalam__bn.txt"
ren "bg.zone" "bulgaria__bg.txt"
ren "bf.zone" "burkina_Faso__bf.txt"
ren "bi.zone" "burundi__bi.txt"
ren "kh.zone" "cambodia__kh.txt"
ren "cm.zone" "cameroon__cm.txt"
ren "ca.zone" "canada__ca.txt"
ren "cv.zone" "cape_verde__cv.txt"
ren "ky.zone" "cayman_islands__ky.txt"
ren "cf.zone" "central_african_republic__cf.txt"
ren "td.zone" "chad__td.txt"
ren "cl.zone" "chile__cl.txt"
ren "cn.zone" "china__cn.txt"
ren "co.zone" "colombia__co.txt"
ren "km.zone" "comoros__km.txt"
ren "cd.zone" "congo_the_democratic_republic_of_the__cd.txt"
ren "cg.zone" "congo__cg.txt"
ren "ck.zone" "cook_islands__ck.txt"
ren "cr.zone" "costa_rica__cr.txt"
ren "ci.zone" "cote_d_ivoire__ci.txt"
ren "hr.zone" "croatia__hr.txt"
ren "cu.zone" "cuba__cu.txt"
ren "cw.zone" "curacao__cw.txt"
ren "cy.zone" "cyprus__cy.txt"
ren "cz.zone" "czech_republic__cz.txt"
ren "dk.zone" "denmark__dk.txt"
ren "dj.zone" "djibouti__dj.txt"
ren "do.zone" "dominican_republic__do.txt"
ren "dm.zone" "dominica__dm.txt"
ren "ec.zone" "ecuador__ec.txt"
ren "eg.zone" "egypt__eg.txt"
ren "sv.zone" "el_salvador__sv.txt"
ren "gq.zone" "equatorial_guinea__gq.txt"
ren "er.zone" "eritrea__er.txt"
ren "ee.zone" "estonia__ee.txt"
ren "et.zone" "ethiopia__et.txt"
ren "eu.zone" "europe_other_ranges_that_were_not_specified__eu.txt"
ren "fk.zone" "falkland_islands_malvinas__fk.txt"
ren "fo.zone" "faroe_islands__fo.txt"
ren "fj.zone" "fiji__fj.txt"
ren "fi.zone" "finland__fi.txt"
ren "fr.zone" "france__fr.txt"
ren "gf.zone" "french_guiana__gf.txt"
ren "pf.zone" "french_polynesia__pf.txt"
ren "ga.zone" "gabon__ga.txt"
ren "gm.zone" "gambia__gm.txt"
ren "ge.zone" "georgia__ge.txt"
ren "de.zone" "germany__de.txt"
ren "gh.zone" "ghana__gh.txt"
ren "gi.zone" "gibraltar__gi.txt"
ren "gr.zone" "greece__gr.txt"
ren "gl.zone" "greenland__gl.txt"
ren "gd.zone" "grenada__gd.txt"
ren "gp.zone" "guadeloupe__gp.txt"
ren "gu.zone" "guam__gu.txt"
ren "gt.zone" "guatemala__gt.txt"
ren "gg.zone" "guernsey_st_peter_port__gg.txt"
ren "gw.zone" "guinea_bissau__gw.txt"
ren "gn.zone" "guinea__gn.txt"
ren "gy.zone" "guyana__gy.txt"
ren "ht.zone" "haiti__ht.txt"
ren "va.zone" "holy_see_vatican_city_state__va.txt"
ren "hn.zone" "honduras__hn.txt"
ren "hk.zone" "hong_kong__hk.txt"
ren "hu.zone" "hungary__hu.txt"
ren "is.zone" "iceland__is.txt"
ren "in.zone" "india__in.txt"
ren "id.zone" "indonesia__id.txt"
ren "ir.zone" "iran_islamic_republic_of__ir.txt"
ren "iq.zone" "iraq__iq.txt"
ren "ie.zone" "ireland__ie.txt"
ren "im.zone" "isle_of_man__im.txt"
ren "il.zone" "israel__il.txt"
ren "it.zone" "italy__it.txt"
ren "jm.zone" "jamaica__jm.txt"
ren "jp.zone" "japan__jp.txt"
ren "je.zone" "jersey__je.txt"
ren "jo.zone" "jordan__jo.txt"
ren "kz.zone" "kazakhstan__kz.txt"
ren "ke.zone" "kenya__ke.txt"
ren "ki.zone" "kiribati__ki.txt"
ren "kp.zone" "korea_democratic_peoples_republic_of__kp.txt"
ren "kr.zone" "korea_republic_of__kr.txt"
ren "kw.zone" "kuwait__kw.txt"
ren "kg.zone" "kyrgyzstan__kg.txt"
ren "ax.zone" "land_islands__ax.txt"
ren "la.zone" "lao_peoples_democratic_republic__la.txt"
ren "lv.zone" "latvia__lv.txt"
ren "lb.zone" "lebanon__lb.txt"
ren "ls.zone" "lesotho__ls.txt"
ren "lr.zone" "liberia__lr.txt"
ren "ly.zone" "libyan_arab_jamahiriya__ly.txt"
ren "li.zone" "liechtenstein__li.txt"
ren "lt.zone" "lithuania__lt.txt"
ren "lu.zone" "luxembourg__lu.txt"
ren "mo.zone" "macao__mo.txt"
ren "mk.zone" "macedonia_the_former_yugoslav_republic_of__mk.txt"
ren "mg.zone" "madagascar__mg.txt"
ren "mw.zone" "malawi__mw.txt"
ren "my.zone" "malaysia__my.txt"
ren "mv.zone" "maldives__mv.txt"
ren "ml.zone" "mali__ml.txt"
ren "mt.zone" "malta__mt.txt"
ren "mh.zone" "marshall_islands__mh.txt"
ren "mq.zone" "martinique__mq.txt"
ren "mr.zone" "mauritania__mr.txt"
ren "mu.zone" "mauritius__mu.txt"
ren "yt.zone" "mayotte__yt.txt"
ren "mx.zone" "mexico__mx.txt"
ren "mf.zone" "saint_martin__mf.txt"
ren "fm.zone" "micronesia_federated_states_of__fm.txt"
ren "md.zone" "moldova_republic_of__md.txt"
ren "mc.zone" "monaco__mc.txt"
ren "mn.zone" "mongolia__mn.txt"
ren "me.zone" "montenegro__me.txt"
ren "ms.zone" "montserrat__ms.txt"
ren "ma.zone" "morocco__ma.txt"
ren "mz.zone" "mozambique__mz.txt"
ren "mm.zone" "myanmar__mm.txt"
ren "na.zone" "namibia__na.txt"
ren "nr.zone" "nauru__nr.txt"
ren "np.zone" "nepal__np.txt"
ren "nl.zone" "netherlands__nl.txt"
ren "nc.zone" "new_caledonia__nc.txt"
ren "nz.zone" "new_zealand__nz.txt"
ren "ni.zone" "nicaragua__ni.txt"
ren "ng.zone" "nigeria__ng.txt"
ren "ne.zone" "niger__ne.txt"
ren "nu.zone" "niue__nu.txt"
ren "nf.zone" "norfolk_island__nf.txt"
ren "mp.zone" "northern_mariana_islands__mp.txt"
ren "no.zone" "norway__no.txt"
ren "om.zone" "oman__om.txt"
ren "pk.zone" "pakistan__pk.txt"
ren "pw.zone" "palau__pw.txt"
ren "ps.zone" "palestinian_territory__ps.txt"
ren "pa.zone" "panama__pa.txt"
ren "pg.zone" "papua_new_guinea__pg.txt"
ren "py.zone" "paraguay__py.txt"
ren "pe.zone" "peru__pe.txt"
ren "ph.zone" "philippines__ph.txt"
ren "pl.zone" "poland__pl.txt"
ren "pt.zone" "portugal__pt.txt"
ren "pr.zone" "puerto_rico__pr.txt"
ren "qa.zone" "qatar__qa.txt"
ren "re.zone" "reunion__re.txt"
ren "ro.zone" "romania__ro.txt"
ren "ru.zone" "russian_federation__ru.txt"
ren "rw.zone" "rwanda__rw.txt"
ren "bl.zone" "saint_barthelemy__bl.txt"
ren "kn.zone" "saint_kitts_and_nevis__kn.txt"
ren "lc.zone" "saint_lucia__lc.txt"
ren "pm.zone" "saint_pierre_and_miquelon__pm.txt"
ren "vc.zone" "saint_vincent_and_the_grenadines__vc.txt"
ren "ws.zone" "samoa__ws.txt"
ren "sm.zone" "san_marino__sm.txt"
ren "st.zone" "sao_tome_and_principe__st.txt"
ren "sa.zone" "saudi_arabia__sa.txt"
ren "sn.zone" "senegal__sn.txt"
ren "rs.zone" "serbia__rs.txt"
ren "sc.zone" "seychelles__sc.txt"
ren "sl.zone" "sierra_leone__sl.txt"
ren "sg.zone" "singapore__sg.txt"
ren "sx.zone" "sint_maarten_dutch_part__sx.txt"
ren "sk.zone" "slovakia__sk.txt"
ren "si.zone" "slovenia__si.txt"
ren "sb.zone" "solomon_islands__sb.txt"
ren "so.zone" "somalia__so.txt"
ren "za.zone" "south_africa__za.txt"
ren "ss.zone" "south_sudan_the_republic_of__ss.txt"
ren "es.zone" "spain__es.txt"
ren "lk.zone" "sri_lanka__lk.txt"
ren "sd.zone" "sudan__sd.txt"
ren "sr.zone" "suriname__sr.txt"
ren "sz.zone" "swaziland__sz.txt"
ren "se.zone" "sweden__se.txt"
ren "ch.zone" "switzerland__ch.txt"
ren "sy.zone" "syrian_arab_republic__sy.txt"
ren "tw.zone" "taiwan__tw.txt"
ren "tj.zone" "tajikistan__tj.txt"
ren "tz.zone" "tanzania_united_republic_of__tz.txt"
ren "th.zone" "thailand__th.txt"
ren "tl.zone" "timor_leste__tl.txt"
ren "tg.zone" "togo__tg.txt"
ren "tk.zone" "tokelau__tk.txt"
ren "to.zone" "tonga__to.txt"
ren "tt.zone" "trinidad_and_tobago__tt.txt"
ren "tn.zone" "tunisia__tn.txt"
ren "tr.zone" "turkey__tr.txt"
ren "tm.zone" "turkmenistan__tm.txt"
ren "tc.zone" "turks_and_caicos_islands__tc.txt"
ren "tv.zone" "tuvalu__tv.txt"
ren "ug.zone" "uganda__ug.txt"
ren "ua.zone" "ukraine__ua.txt"
ren "ae.zone" "united_arab_emirates__ae.txt"
ren "gb.zone" "united_kingdom__gb.txt"
ren "us.zone" "united_states__us.txt"
ren "uy.zone" "uruguay__uy.txt"
ren "uz.zone" "uzbekistan__uz.txt"
ren "vu.zone" "vanuatu__vu.txt"
ren "ve.zone" "venezuela__ve.txt"
ren "vn.zone" "viet_nam__vn.txt"
ren "vg.zone" "virgin_islands_british__vg.txt"
ren "vi.zone" "virgin_islands_u_s__vi.txt"
ren "wf.zone" "wallis_and_futuna__wf.txt"
ren "ye.zone" "yemen__ye.txt"
ren "zm.zone" "zambia__zm.txt"
ren "zw.zone" "zimbabwe__zw.txt"


for %%e in (*.txt) do ( 
  call "%HOME%\..\cidr_notation_to_ip_ranges\index.cmd" "%%~e"
)

move /y "*.txt" "%HOME%\..\..\lists_1_country\"
